### ISSUE TITLE
CSS Attributes

### ISSUE THREAD

**Issue by Pet3ris** [giraud/bs-css#210]
Hi There,

For some CSS parameters (like setting padding on an input field), one needs to use CSS attributes like so:

```
input[type="text"] {
   padding:20px;
}
```

Is this possible in `bs-css`?

**Comment by lucasweng** [comment]
hi @Pet3ris,

There's a `selector` for using CSS attributes, and depending on the module you're using, the input example can be written like so:

**Css**
```reason
// .re files
open Css;

let styles = style([selector("input[type='text']", [padding(px(20))])]);
```

https://github.com/reasonml-labs/bs-css/blob/c31b8fb7cfa1d84abd19babc60d5035289b2cf02/bs-css/src/Css_Legacy_Core.rei#L1088


**CssJs**
```reason
// .re files
open CssJs;

let styles = style(. [|selector("input[type='text']", [|padding(px(20))|])|]);
```

https://github.com/reasonml-labs/bs-css/blob/c31b8fb7cfa1d84abd19babc60d5035289b2cf02/bs-css/src/Css_Js_Core.rei#L1087

Some .res example here:
https://github.com/reasonml-labs/bs-css/blob/c31b8fb7cfa1d84abd19babc60d5035289b2cf02/bs-css-emotion/example/Section.res#L13-L23

**Comment by Pet3ris** [comment]
Thanks a lot @lucasweng !

**Comment by giraud** [comment]
added to README
