### ISSUE TITLE
justify-items is not supported

### ISSUE THREAD

**Issue by rusty-key** [giraud/bs-css#212]
https://developer.mozilla.org/en-US/docs/Web/CSS/justify-items

```ml
justifyItems `start
```
↓
```
Unbound value justifyItems
```

**Comment by rusty-key** [comment]
Looks like `place-items` is not supported either:
https://developer.mozilla.org/en-US/docs/Web/CSS/place-items

**Comment by giraud** [comment]
yep, PR welcome.
