### ISSUE TITLE
SVG rules are hard to discover

### ISSUE THREAD

**Issue by rusty-key** [giraud/bs-css#218]
@giraud, is there a reason SVG-related rules are hidden in the module? Since we switched to `bs-css` I had multiple complaints from my coworkers about lack of support for rules like `stroke` and `fill` and I had to point them out to this module. 
https://github.com/reasonml-labs/bs-css/blob/64ee12c445fcd84ea1149d30ebced7deeec65ce8/bs-css/src/Css_Js_Core.rei#L1884-L1896

**Comment by giraud** [comment]
@rusty-key only reason is that I have no interest in it and it has never been really updated/synchronized. 
SVG sure need some work, PR welcome.

**Comment by hoichi** [comment]
One possible issue with getting the SVG rules out of the namespace is that [there is already a value called `fill`](https://github.com/reasonml-labs/bs-css/blob/master/bs-css/src/Css_Legacy_Core.re#L1486), so you're gonna have to disambiguate between the two.
