### ISSUE TITLE
vendor-specific properties

### ISSUE THREAD

**Issue by rusty-key** [giraud/bs-css#221]
@giraud, what's your opinion on vendor-specific prefixes? 
I took a look at our codebase and I see many usages of `-webkit-appearance` and `-webkit-overflow-scrolling`. I know it's potentially a can of worms (if we add support for these properties, why not add it for everything). But maybe `bs-css` should cover some of the specialized props that do not have standard alternatives? For example, don't cover `-webkit-flex`/`-ms-flex` etc, but cover `-webkit-overflow-scrolling`? What do you think?

**Comment by giraud** [comment]
I prefer to not have any vendor prefix in the lib, there is always the possibility to create a function with `unsafe` in user app.
