### ISSUE TITLE
Move to @rescript/react (from reason-react)

### ISSUE THREAD

**Issue by JasoonS** [giraud/bs-css#236]
Hi, do you have any objections to moving to [`@rescript/react`](https://github.com/rescript-lang/rescript-react/blob/master/Changes.md) for the next release?

I can prep a PR if that would help :)

**Comment by giraud** [comment]
Hi, it's a dev dependency, so it has no impact on release.
send a PR to see the changes

**Comment by JasoonS** [comment]
Sure, local opens do make this library easier to use. I don't mind waiting, I just don't know the timeline on that.

**Comment by giraud** [comment]
Hi, I though about it and there is no reason to have a dependency to reason-react or rescript-react in the different packages. 
They are only used during development, for visual verifications (non-reg or tests), and now that there are unit tests in bs-css package, they are less needed.
The safest thing to do would be to create a new unpublished package that contains all the html code for the different implementations. I think it'll be safer to extract react dependency. I'll try.
