### ISSUE TITLE
Global styles get added as quoted strings.

### ISSUE THREAD

**Issue by Froncz** [giraud/bs-css#238]
Hi. After updating the module, we've started facing the problem with global styles. They get added as camel-cased quoted strings.

Have anyone the same problem?

![image](https://user-images.githubusercontent.com/9446363/113837516-39743780-978e-11eb-92e2-b1a6a9648ef7.png)
![image](https://user-images.githubusercontent.com/9446363/113837541-3f6a1880-978e-11eb-9123-63a12cfdb277.png)

**Comment by Freddy03h** [comment]
I've face the same problem.

**Comment by giraud** [comment]
if I change the current `App.res` in `dev-server-emotion` to : 
```
open CssJs
global(. "*", [
    margin(#zero), padding(#zero), backgroundColor(lavender), marginTop(10->px), fontFamily(#custom("Source Sans Pro"))
])
```

I get correct names:
![image](https://user-images.githubusercontent.com/239612/116044732-90747a80-a671-11eb-9c9e-dcdf28bcf5df.png)

what version are you using ?

**Comment by rolandpeelen** [comment]
Same here. Also, none of our global styles are working anymore - we think this might be related. @giraud 's fix works, but it's not ideal.

From:
```
Css.(
  global(
    "html",
    [
      boxSizing(`borderBox),
      selector("*, *:before, *:after", [boxSizing(`inherit_)]),
      selector("::-webkit-scrollbar", [background(`transparent)]),
    ],
  )
);
```

To:
```
CssJs.(
  global(.
    "html",
    [|
      boxSizing(`borderBox),
      selector("*, *:before, *:after", [|boxSizing(`inherit_)|]),
      selector("::-webkit-scrollbar", [|background(`transparent)|]),
    |],
  )
);
```

**Comment by giraud** [comment]
@rolandpeelen what do you mean ? switching from Css to CssJs is the fix ?

**Comment by rolandpeelen** [comment]
@giraud - For us, for just the global Css variants, switching to `CssJs` works (we only have two global css statements, so that's fine).

**Comment by giraud** [comment]
ah yes, there is a diff in impl:

js:
![image](https://user-images.githubusercontent.com/239612/120605605-8acb3b00-c44e-11eb-8565-6de982dd73df.png)

legacy:
![image](https://user-images.githubusercontent.com/239612/120605644-9880c080-c44e-11eb-85b0-8dd114d17395.png)
