### ISSUE TITLE
Issue with Shadow and CssJs

### ISSUE THREAD

**Issue by davesnx** [giraud/bs-css#242]
Hey @giraud 

I found a compiler error that complains about CssJs modules being aliases to Css_Js_Core modules and those are missing.

```re
CssJs.style(. [|
  CssJs.boxShadows([|
	CssJs.Shadow.box(yellow), CssJs.Shadow.box(red)
  |])
|]);
```

```The module CssJs.Shadow is an alias for module Css_Js_Core.Shadow, which is missing```

This happens with `bs-css-emotion@2.5.1` and `bs-platform@8.2.1`. Let me know if there's something wrong here.

Thanks!

**Comment by giraud** [comment]
No problem in my tests. 

my setup: `bs-css@14.0.1`, `bs-css-emotion@2.5.1`, `bs-platform@8.2.0` (There is no bs-platform @ `8.2.1`). I copied your code and build is ok, no warnings.

Can you check your `yarn.lock` for resolved versions of `bs-css` and `bs-css-emotion` ?

**Comment by davesnx** [comment]
My bad, didn't add bs-css into bsconfig. I didn't realize those are module-dependant.

Thanks for the fast response.

**Comment by davesnx** [comment]
When I build the project I still get the duplicated packages, `bs-css@14.0.1, bs-css-emotion@2.5.1`

Duplicated package: bs-css /Users/davesnx/Code/github/query-json/node_modules/bs-css (chosen) vs /Users/davesnx/Code/github/query-json/node_modules/bs-css-emotion/node_modules/bs-css in /Users/davesnx/Code/github/query-json/node_modules/bs-css-emotion

Isn't a huge issue, since build keep working.

**Comment by giraud** [comment]
@davesnx you must have multiple definitions in your yarn.lock (or npm equivalent ?).
if using yarn, maybe a `yarn why bs-css` can give you pointer why it's duplicated
