### ISSUE TITLE
Allow bs-css-emotion to take a custom cache

### ISSUE THREAD

**Issue by joshgodsiff** [giraud/bs-css#245]
I have a use-case where we end up multiple instances of `emotion` loaded, with the result that the default internal caches conflict with each other when doing server-side rendering.

I'm currently hacking around this by creating new instances of emotion with non-conflicting caches using `@emotion/css/create-instance`, and then creating fresh custom bindings in Reason, but that's not ideal for many reasons.

It'd be awesome if the `bs-css-emotion` bindings could take a custom cache as a parameter somehow.

**Comment by giraud** [comment]
@joshgodsiff I'm not using cache and have no idea how that work, but a PR is welcome to solve that point.
