### ISSUE TITLE
is this library focused on ReScript?

### ISSUE THREAD

**Issue by vmarcosp** [giraud/bs-css#259]
I'm asking because I would suggest to rename from `bs-css` to `rescript-css`. For the newcomers it's easy to find the library if the repo makes it clear that the library is focused on ReScript. The `bs-*` prefix was very intuitive and useful when the compiler was called BuckleScript, but now that we have a new brand for ReScript, doesn't make sense to rename this package?
Please, if you agree, let me know how I can help you with this change.

**Comment by giraud** [comment]
Hi, I have no plan to rename that library, and hope it'll continue to work with both reason and rescript projects as much as possible.

**Comment by vmarcosp** [comment]
Oh, got it @giraud, thanks for answering.
> ...hope it'll continue to work with both reason and rescript projects as much as possible.

Even on rescript v10 that the reason syntax will be removed? (I'm not if will be on v10 or v11).

**Comment by giraud** [comment]
I hope that [melange](https://github.com/melange-re/melange) will be able to consume rescript files  in the future. This project is using only basic syntax, nothing advanced.

**Comment by vmarcosp** [comment]
Thanks for answering!
