### ISSUE TITLE
contentRule (`text "foo")

### ISSUE THREAD

**Issue by davesnx** [giraud/bs-css#263]
Hi,

`contentRule (``text "•")` it yields at runtime:

```
Uncaught Error:
You seem to be using a value for 'content' without quotes, try replacing it with `content: '"•"'`
```

This happens since it transforms to `content: ""` in JavaScript instead of `content: '""'`. Would make sense to have string_of_content to add quotes? (Maybe add quotes when missing?)

**Comment by davesnx** [comment]
For anyone reading, the fix is to add quotes:

ReasonML
```contentRule(`text({js|" "|js}));```

OCaml
```contentRule (`text {js|" "|js});```

ReScript
```contentRule(#text(`" "`);```

**Comment by giraud** [comment]
it used to be working 😕 something changed
